### ISSUE TITLE
Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogShipper

### ISSUE THREAD

**Issue by Venkateshjsoft** [serilog-contrib/serilog-sinks-elasticsearch#259]
2019-07-11T09:24:35.2593454Z Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogShipper: System.MissingMethodException: Method not found: '!!0 Elasticsearch.Net.ElasticLowLevelClient.IndicesPutTemplateForAll(System.String, Elasticsearch.Net.PostData, Elasticsearch.Net.PutIndexTemplateRequestParameters)'.
at Serilog.Sinks.Elasticsearch.ElasticsearchSinkState.RegisterTemplateIfNeeded()
at Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogShipper.d__3.MoveNext()

**Comment by mivano** [comment]
Bit hard to help you with this. Looks like an incorrect dependency inside your project. Can you reproduce inside an empty/new project?

**Comment by Venkateshjsoft** [comment]
Please find the selflog.
2019-08-04T07:48:58.6641062Z Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogShipper: System.MissingMethodException: Method not found: '!!0 Elasticsearch.Net.ElasticLowLevelClient.IndicesPutTemplateForAll(System.String, Elasticsearch.Net.PostData, Elasticsearch.Net.PutIndexTemplateRequestParameters)'.
   at Serilog.Sinks.Elasticsearch.ElasticsearchSinkState.RegisterTemplateIfNeeded()
   at Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogShipper.<OnTick>d__3.MoveNext()
