### ISSUE TITLE
Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogShipper

### ISSUE THREAD

**Issue by Venkateshjsoft** [serilog-contrib/serilog-sinks-elasticsearch#262]
2019-07-11T09:24:35.2593454Z Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogShipper: System.MissingMethodException: Method not found: '!!0 Elasticsearch.Net.ElasticLowLevelClient.IndicesPutTemplateForAll(System.String, Elasticsearch.Net.PostData, Elasticsearch.Net.PutIndexTemplateRequestParameters)'.
   at Serilog.Sinks.Elasticsearch.ElasticsearchSinkState.RegisterTemplateIfNeeded()
   at Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogShipper.<OnTick>d__3.MoveNext()

**Comment by Venkateshjsoft** [comment]
Hi Nicholas Blumhardt,
Please find my package configuration
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Elasticsearch.Net" version="7.0.1" targetFramework="net472" />
  <package id="Serilog" version="2.8.0" targetFramework="net472" />
  <package id="Serilog.Formatting.Compact" version="1.0.0" targetFramework="net472" />
  <package id="Serilog.Formatting.Elasticsearch" version="7.1.0" targetFramework="net472" />
  <package id="Serilog.Sinks.Elasticsearch" version="7.1.0" targetFramework="net472" />
  <package id="Serilog.Sinks.File" version="4.0.0" targetFramework="net472" />
  <package id="Serilog.Sinks.PeriodicBatching" version="2.1.1" targetFramework="net472" />
  <package id="System.Buffers" version="4.5.0" targetFramework="net472" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.5.1" targetFramework="net472" />
</packages>

**Comment by Venkateshjsoft** [comment]
Please find the selflog 
2019-08-04T07:48:58.6641062Z Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogShipper: System.MissingMethodException: Method not found: '!!0 Elasticsearch.Net.ElasticLowLevelClient.IndicesPutTemplateForAll(System.String, Elasticsearch.Net.PostData, Elasticsearch.Net.PutIndexTemplateRequestParameters)'.
   at Serilog.Sinks.Elasticsearch.ElasticsearchSinkState.RegisterTemplateIfNeeded()
   at Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogShipper.<OnTick>d__3.MoveNext()

**Comment by mivano** [comment]
Do check that the package of elasticsearch.net that ends up in your bin folder is indeed the one you would expect. Other dependencies might have pulled in a different version. It is hard to pin point your issues. Try to create a new project and see if you can reproduce?
