### ISSUE TITLE
Cannot log to ElasticSearch v7.16.2

### ISSUE THREAD

**Issue by codingbutcher** [serilog-contrib/serilog-sinks-elasticsearch#404]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
- Serilog.Sinks.Elasticsearch v8.4.1

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netCore 3.1
- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
* Logging to Elasticsearch was operating as expected on v7.15.1 (and older)
* We upgraded to the latest build of Elasticsearch v7.16.2
* Logging is failing to write to ElasticSearch
* Enabling SelfLog via:
```
var file = System.IO.File.CreateText("./Logs/SysLog.TextLog.txt");
 Serilog.Debugging.SelfLog.Enable(System.IO.TextWriter.Synchronized(file));
```
* Resulting Error:
```
2022-01-05T21:28:38.3639130Z Caught exception while preforming bulk operation to Elasticsearch: Elasticsearch.Net.ElasticsearchClientException: Could not authenticate with the specified node. Try verifying your credentials or check your Shield configuration.. Call: Status code 401 from: POST /_bulk. ServerError: Type: security_exception Reason: "missing authentication credentials for REST request [/_bulk]"
 ---> Elasticsearch.Net.PipelineException: Could not authenticate with the specified node. Try verifying your credentials or check your Shield configuration.
   at Elasticsearch.Net.RequestPipeline.ThrowBadAuthPipelineExceptionWhenNeeded(IApiCallDetails details, IElasticsearchResponse response)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.HandleElasticsearchClientException(RequestData data, Exception clientException, IElasticsearchResponse response)
   at Elasticsearch.Net.Transport`1.FinalizeResponse[TResponse](RequestData requestData, IRequestPipeline pipeline, List`1 seenExceptions, TResponse response)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatchAsync(IEnumerable`1 events)
2022-01-05T21:28:40.4191360Z Caught exception while preforming bulk operation to Elasticsearch: Elasticsearch.Net.ElasticsearchClientException: Could not authenticate with the specified node. Try verifying your credentials or check your Shield configuration.. Call: Status code 401 from: POST /_bulk. ServerError: Type: security_exception Reason: "missing authentication credentials for REST request [/_bulk]"
 ---> Elasticsearch.Net.PipelineException: Could not authenticate with the specified node. Try verifying your credentials or check your Shield configuration.
   at Elasticsearch.Net.RequestPipeline.ThrowBadAuthPipelineExceptionWhenNeeded(IApiCallDetails details, IElasticsearchResponse response)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.HandleElasticsearchClientException(RequestData data, Exception clientException, IElasticsearchResponse response)
   at Elasticsearch.Net.Transport`1.FinalizeResponse[TResponse](RequestData requestData, IRequestPipeline pipeline, List`1 seenExceptions, TResponse response)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatchAsync(IEnumerable`1 events)
```

**Additional Debug Actions Taken**
* Confirmed Username/Password is working with Elasticsearch _bulk command via running a simple command example POST API call (in Postman)
* Failure only occurs via the Serilog code usage
* Confirmed writing from the Elasticsearch indexes is working fine via other code which populates data to ES.
* Confirmed same code works when pointed to a older version of Elasticsearch (changing the end point via the settings)

**Please describe the expected behavior?**
* Logging should write to the Elasticsearch v7.16.2

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
* Specific to Elasticsearch v7.16.2
* Test file creates the Logger instance, writes to the log and forces a terminating exception to confirm only a single log is pushed to confirm the test case.

appsettings.json
```
...
 "Serilog": {
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Warning",
        "System": "Warning"
      }
    },
    "WriteTo": [
        { "Name": "Console" },
      {
        "Name": "File",
        "Args": {
          "restrictedToMinimumLevel": "Debug",
          "path": "Logs/logs_.log",
          "rollingInterval": "Day",
          "retainedFileCountLimit": 31
        }
      },
      {
        "Name": "Elasticsearch",
        "Args": {
            "restrictedToMinimumLevel": "Information",
            "nodeUris": "<<<ES INSTANCE>>",
            "indexFormat": "application_logs-{0:yyyy.MM.dd}",
            "autoRegisterTemplate": false,
            "autoRegisterTemplateVersion": "ESv2",
            "username": "<<USERNAME>>",
            "password": "<<PASSWORD>>"
        }
      }
    ]
  }
...
```

Startup.cs
```
public Startup(IConfiguration configuration, IServiceProvider provider)
        {
            var logConfiguration = new LoggerConfiguration()
               .Enrich.WithAspnetcoreHttpcontext(provider)
                .ReadFrom.Configuration(configuration);

            Log.Logger = logConfiguration.CreateLogger();
            Configuration = configuration;

            var file = System.IO.File.CreateText("./Logs/SysLog.TextLog.txt");
            Serilog.Debugging.SelfLog.Enable(System.IO.TextWriter.Synchronized(file));

            Log.Logger.Information(new ApplicationException("This is working!").ToString());

            throw new Exception("BOOM - forced stopping.");
        }
```

**Comment by codingbutcher** [comment]
Determined the cause was the Authentication syntax in the Appsettings was incorrect.  Specifically the sytax of the **nodeUris** parameter.

Keeping this ticket in full for any future issues someone may have which is similar:

```
"Args": {
            "restrictedToMinimumLevel": "Information",
            "nodeUris": "https://<<USERNAME>>:<<PASSWORD>>@<<ES INSTANCE>>",
            "indexFormat": "application_logs_guardian_insights-{0:yyyy.MM.dd}",
            "autoRegisterTemplate": false,
            "autoRegisterTemplateVersion": "ESv2",
            "username": "<<USERNAME>>",
            "password": "<<PASSWORD>>"
        }
```
